C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 22 Aug 2023 15:51
C
C  Differentiation of calc_stab_derivs in reverse (adjoint) mode (with options i4 dr8 r8):
C   gradient     of useful results: cftot_d cxtot_u_ba cytot_u_ba
C                cztot_u_ba cxtot_d_ba cytot_d_ba cztot_d_ba cmtot
C                cmtot_d crsax_d cmsax_d cnsax_d crtot_u_ba cmtot_u_ba
C                cntot_u_ba crtot_d_ba cmtot_d_ba cntot_d_ba cdtot_al
C                cltot_al cytot_al crtot_al cmtot_al cntot_al cdtot_be
C                cltot_be cytot_be crtot_be cmtot_be cntot_be cdtot_rx
C                cltot_rx cytot_rx crtot_rx cmtot_rx cntot_rx cdtot_ry
C                cltot_ry cytot_ry crtot_ry cmtot_ry cntot_ry cdtot_rz
C                cltot_rz cytot_rz crtot_rz cmtot_rz cntot_rz xnp
C                sm bb rr
C   with respect to varying inputs: alfa vinf_a vinf_b wrot cref
C                bref xyzref cdtot_a cltot_a cdtot_u cytot_u cltot_u
C                cftot_u cftot_d cxtot_u_ba cytot_u_ba cztot_u_ba
C                cxtot_d_ba cytot_d_ba cztot_d_ba cmtot cmtot_u
C                cmtot_d crsax_d cmsax_d cnsax_d crtot_u_ba cmtot_u_ba
C                cntot_u_ba crtot_d_ba cmtot_d_ba cntot_d_ba xnp
C                sm bb rr
C GETFILE
C
C
C
C ==================== addition wrapper helper programs ==============
C
      SUBROUTINE CALC_STAB_DERIVS_B()
      INCLUDE 'AVL.INC'
      INCLUDE 'AVL_ad_seeds.inc'
      CHARACTER*50 satype
      REAL wrot_rx(3), wrot_rz(3), wrot_a(3)
      REAL wrot_rx_diff(3), wrot_rz_diff(3), wrot_a_diff(3)
      REAL crsax_u(numax), cmsax_u(numax), cnsax_u(numax), crsax_g(ngmax
     +     ), cmsax_g(ngmax), cnsax_g(ngmax)
      REAL crsax_u_diff(numax), cmsax_u_diff(numax), cnsax_u_diff(numax)
      REAL dir
      EXTERNAL GETSA
      REAL ca
      REAL ca_diff
      INTRINSIC COS
      REAL sa
      REAL sa_diff
      INTRINSIC SIN
      REAL rx
      REAL rx_diff
      REAL ry
      REAL rz
      REAL rz_diff
      REAL crsax_a
      REAL crsax_a_diff
      REAL cnsax_a
      REAL cnsax_a_diff
      INTEGER k
      INTRINSIC ABS
      REAL(kind=avl_real) abs0
      REAL(kind=avl_real) abs1
      REAL(kind=avl_real) abs2
      REAL(kind=avl_real) abs2_diff
      REAL(kind=avl_real) temp_diff
      INTEGER ii1
      REAL(kind=avl_real) temp_diff0
      INTEGER ii2
      INTEGER*4 branch
C
C CALL VINFAB
C CALL AERO
      CALL GETSA(lnasa_sa, satype, dir)
C
C---- set freestream velocity components from alpha, beta
C
C---- calculate forces and sensitivities
C
C---- set stability-axes rates (RX,RY,RZ) in terms of body-axes rates
      ca = COS(alfa)
      sa = SIN(alfa)
C
      rx = (wrot(1)*ca+wrot(3)*sa)*dir
      rz = (wrot(3)*ca-wrot(1)*sa)*dir
C
C---- now vice-versa, and set sensitivities (which is what's really needed)
Cc    WROT(1)    =  RX*CA - RZ*SA
Cc    WROT(2)    =  RY
Cc    WROT(3)    =  RZ*CA + RX*SA
C
      wrot_rx(1) = ca*dir
      wrot_rx(2) = 0.
      wrot_rx(3) = sa*dir
C
      wrot_rz(1) = -(sa*dir)
      wrot_rz(2) = 0.
      wrot_rz(3) = ca*dir
C
C!! = -WROT(3)
      wrot_a(1) = -(rx*sa) - rz*ca
      wrot_a(2) = 0.
C!! =  WROT(1)
      wrot_a(3) = -(rz*sa) + rx*ca
C
C
C
      DO k=1,6
        crsax_u(k) = cmtot_u(1, k)*ca + cmtot_u(3, k)*sa
        cmsax_u(k) = cmtot_u(2, k)
        cnsax_u(k) = cmtot_u(3, k)*ca - cmtot_u(1, k)*sa
      ENDDO
C
C
C---- set force derivatives in stability axes
      cltot_al = cltot_u(1)*vinf_a(1) + cltot_u(4)*wrot_a(1) + cltot_u(2
     +  )*vinf_a(2) + cltot_u(5)*wrot_a(2) + cltot_u(3)*vinf_a(3) + 
     +  cltot_u(6)*wrot_a(3) + cltot_a
      cltot_rx = cltot_u(4)*wrot_rx(1) + cltot_u(6)*wrot_rx(3)
      cltot_ry = cltot_u(5)
      cltot_rz = cltot_u(6)*wrot_rz(3) + cltot_u(4)*wrot_rz(1)
C
      cytot_rx = cytot_u(4)*wrot_rx(1) + cytot_u(6)*wrot_rx(3)
      cytot_ry = cytot_u(5)
      cytot_rz = cytot_u(6)*wrot_rz(3) + cytot_u(4)*wrot_rz(1)
C
      cdtot_rx = cdtot_u(4)*wrot_rx(1) + cdtot_u(6)*wrot_rx(3)
      cdtot_ry = cdtot_u(5)
      cdtot_rz = cdtot_u(6)*wrot_rz(3) + cdtot_u(4)*wrot_rz(1)
C
      crtot_be = crsax_u(1)*vinf_b(1) + crsax_u(2)*vinf_b(2) + crsax_u(3
     +  )*vinf_b(3)
      crtot_rx = crsax_u(4)*wrot_rx(1) + crsax_u(6)*wrot_rx(3)
      crtot_ry = crsax_u(5)
      crtot_rz = crsax_u(6)*wrot_rz(3) + crsax_u(4)*wrot_rz(1)
C
      cmtot_al = cmsax_u(1)*vinf_a(1) + cmsax_u(4)*wrot_a(1) + cmsax_u(2
     +  )*vinf_a(2) + cmsax_u(5)*wrot_a(2) + cmsax_u(3)*vinf_a(3) + 
     +  cmsax_u(6)*wrot_a(3)
      cmtot_rx = cmsax_u(4)*wrot_rx(1) + cmsax_u(6)*wrot_rx(3)
      cmtot_ry = cmsax_u(5)
      cmtot_rz = cmsax_u(6)*wrot_rz(3) + cmsax_u(4)*wrot_rz(1)
C
      cntot_be = cnsax_u(1)*vinf_b(1) + cnsax_u(2)*vinf_b(2) + cnsax_u(3
     +  )*vinf_b(3)
      cntot_rx = cnsax_u(4)*wrot_rx(1) + cnsax_u(6)*wrot_rx(3)
      cntot_ry = cnsax_u(5)
C apply the facotors to the outputs as done in the print statements of DERMATS
      cntot_rz = cnsax_u(6)*wrot_rz(3) + cnsax_u(4)*wrot_rz(1)
C
C        
C
      crtot_be = dir*crtot_be
      cntot_be = dir*cntot_be
C
C
      CALL PUSHREAL8(crtot_rz)
      crtot_rz = dir*crtot_rz*2.0/bref
      CALL PUSHREAL8(cntot_rz)
      cntot_rz = dir*cntot_rz*2.0/bref
C
      IF (cltot_al .NE. 0.0) THEN
C  XNP = XYZREF(1) - CREF*CMTOT_AL/CLTOT_AL
C  SM = (XNP - XYZREF(1))/CREF This is the same as below
        sm = -(cmtot_al/cltot_al)
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
      IF (crtot_rz*cntot_be .GE. 0.) THEN
        abs0 = crtot_rz*cntot_be
      ELSE
        abs0 = -(crtot_rz*cntot_be)
      END IF
C
      IF (abs0 .GT. 0.0) THEN
        CALL PUSHCONTROL1B(1)
      ELSE
        CALL PUSHCONTROL1B(0)
      END IF
      IF (crtot_be .GE. 0.) THEN
        abs1 = crtot_be
      ELSE
        abs1 = -crtot_be
      END IF
C ---- body axis derivatives
C these expressions are taken from DERMATB
C'  axial   vel. u', ' sideslip vel. v', '  normal  vel. w'
      IF (abs1 .GT. 0.0) THEN
        IF (crtot_be .GE. 0.) THEN
          abs2 = crtot_be
          CALL PUSHCONTROL1B(0)
        ELSE
          abs2 = -crtot_be
          CALL PUSHCONTROL1B(1)
        END IF
        CALL PUSHCONTROL1B(0)
      ELSE
        CALL PUSHCONTROL1B(1)
      END IF
      DO k=ncontrol,1,-1
        cmtot_d_diff(3, k) = cmtot_d_diff(3, k) + dir*cntot_d_ba_diff(k)
        cntot_d_ba_diff(k) = 0.D0
        cmtot_d_diff(2, k) = cmtot_d_diff(2, k) + cmtot_d_ba_diff(k)
        cmtot_d_ba_diff(k) = 0.D0
        cmtot_d_diff(1, k) = cmtot_d_diff(1, k) + dir*crtot_d_ba_diff(k)
        crtot_d_ba_diff(k) = 0.D0
        cftot_d_diff(3, k) = cftot_d_diff(3, k) + dir*cztot_d_ba_diff(k)
        cztot_d_ba_diff(k) = 0.D0
        cftot_d_diff(2, k) = cftot_d_diff(2, k) + cytot_d_ba_diff(k)
        cytot_d_ba_diff(k) = 0.D0
        cftot_d_diff(1, k) = cftot_d_diff(1, k) + dir*cxtot_d_ba_diff(k)
        cxtot_d_ba_diff(k) = 0.D0
      ENDDO
      DO ii1=1,numax
        DO ii2=1,3
          cmtot_u_diff(ii2, ii1) = 0.D0
        ENDDO
      ENDDO
      temp_diff0 = 2.0*cntot_u_ba_diff(6)/bref
      cntot_u_ba_diff(6) = 0.D0
      cmtot_u_diff(3, 6) = cmtot_u_diff(3, 6) + temp_diff0
      bref_diff = -(cmtot_u(3, 6)*temp_diff0/bref)
      temp_diff0 = dir*2.0*cntot_u_ba_diff(5)/cref
      cntot_u_ba_diff(5) = 0.D0
      cmtot_u_diff(3, 5) = cmtot_u_diff(3, 5) + temp_diff0
      cref_diff = -(cmtot_u(3, 5)*temp_diff0/cref)
      temp_diff0 = 2.0*cntot_u_ba_diff(4)/bref
      cntot_u_ba_diff(4) = 0.D0
      cmtot_u_diff(3, 4) = cmtot_u_diff(3, 4) + temp_diff0
      bref_diff = bref_diff - cmtot_u(3, 4)*temp_diff0/bref
      temp_diff0 = dir*2.0*cmtot_u_ba_diff(6)/bref
      cmtot_u_ba_diff(6) = 0.D0
      cmtot_u_diff(2, 6) = cmtot_u_diff(2, 6) + temp_diff0
      bref_diff = bref_diff - cmtot_u(2, 6)*temp_diff0/bref
      temp_diff0 = 2.0*cmtot_u_ba_diff(5)/cref
      cmtot_u_ba_diff(5) = 0.D0
      cmtot_u_diff(2, 5) = cmtot_u_diff(2, 5) + temp_diff0
      cref_diff = cref_diff - cmtot_u(2, 5)*temp_diff0/cref
      temp_diff0 = dir*2.0*cmtot_u_ba_diff(4)/bref
      cmtot_u_ba_diff(4) = 0.D0
      cmtot_u_diff(2, 4) = cmtot_u_diff(2, 4) + temp_diff0
      bref_diff = bref_diff - cmtot_u(2, 4)*temp_diff0/bref
      temp_diff0 = 2.0*crtot_u_ba_diff(6)/bref
      crtot_u_ba_diff(6) = 0.D0
      cmtot_u_diff(1, 6) = cmtot_u_diff(1, 6) + temp_diff0
      bref_diff = bref_diff - cmtot_u(1, 6)*temp_diff0/bref
      temp_diff0 = dir*2.0*crtot_u_ba_diff(5)/cref
      crtot_u_ba_diff(5) = 0.D0
      cmtot_u_diff(1, 5) = cmtot_u_diff(1, 5) + temp_diff0
      cref_diff = cref_diff - cmtot_u(1, 5)*temp_diff0/cref
      temp_diff0 = 2.0*crtot_u_ba_diff(4)/bref
      crtot_u_ba_diff(4) = 0.D0
      cmtot_u_diff(1, 4) = cmtot_u_diff(1, 4) + temp_diff0
      bref_diff = bref_diff - cmtot_u(1, 4)*temp_diff0/bref
      DO ii1=1,numax
        DO ii2=1,3
          cftot_u_diff(ii2, ii1) = 0.D0
        ENDDO
      ENDDO
      temp_diff0 = 2.0*cztot_u_ba_diff(6)/bref
      cztot_u_ba_diff(6) = 0.D0
      cftot_u_diff(3, 6) = cftot_u_diff(3, 6) + temp_diff0
      bref_diff = bref_diff - cftot_u(3, 6)*temp_diff0/bref
      temp_diff0 = dir*2.0*cztot_u_ba_diff(5)/cref
      cztot_u_ba_diff(5) = 0.D0
      cftot_u_diff(3, 5) = cftot_u_diff(3, 5) + temp_diff0
      cref_diff = cref_diff - cftot_u(3, 5)*temp_diff0/cref
      temp_diff0 = 2.0*cztot_u_ba_diff(4)/bref
      cztot_u_ba_diff(4) = 0.D0
      cftot_u_diff(3, 4) = cftot_u_diff(3, 4) + temp_diff0
      bref_diff = bref_diff - cftot_u(3, 4)*temp_diff0/bref
      temp_diff0 = dir*2.0*cytot_u_ba_diff(6)/bref
      cytot_u_ba_diff(6) = 0.D0
      cftot_u_diff(2, 6) = cftot_u_diff(2, 6) + temp_diff0
      bref_diff = bref_diff - cftot_u(2, 6)*temp_diff0/bref
      temp_diff0 = 2.0*cytot_u_ba_diff(5)/cref
      cytot_u_ba_diff(5) = 0.D0
      cftot_u_diff(2, 5) = cftot_u_diff(2, 5) + temp_diff0
      cref_diff = cref_diff - cftot_u(2, 5)*temp_diff0/cref
      temp_diff0 = dir*2.0*cytot_u_ba_diff(4)/bref
      cytot_u_ba_diff(4) = 0.D0
      cftot_u_diff(2, 4) = cftot_u_diff(2, 4) + temp_diff0
      bref_diff = bref_diff - cftot_u(2, 4)*temp_diff0/bref
      temp_diff0 = 2.0*cxtot_u_ba_diff(6)/bref
      cxtot_u_ba_diff(6) = 0.D0
      cftot_u_diff(1, 6) = cftot_u_diff(1, 6) + temp_diff0
      bref_diff = bref_diff - cftot_u(1, 6)*temp_diff0/bref
      temp_diff0 = dir*2.0*cxtot_u_ba_diff(5)/cref
      cxtot_u_ba_diff(5) = 0.D0
      cftot_u_diff(1, 5) = cftot_u_diff(1, 5) + temp_diff0
      cref_diff = cref_diff - cftot_u(1, 5)*temp_diff0/cref
      temp_diff0 = 2.0*cxtot_u_ba_diff(4)/bref
      cxtot_u_ba_diff(4) = 0.D0
      cftot_u_diff(1, 4) = cftot_u_diff(1, 4) + temp_diff0
      bref_diff = bref_diff - cftot_u(1, 4)*temp_diff0/bref
      cmtot_u_diff(3, 3) = cmtot_u_diff(3, 3) - cntot_u_ba_diff(3)
      cntot_u_ba_diff(3) = 0.D0
      cmtot_u_diff(3, 2) = cmtot_u_diff(3, 2) - dir*cntot_u_ba_diff(2)
      cntot_u_ba_diff(2) = 0.D0
      cmtot_u_diff(3, 1) = cmtot_u_diff(3, 1) - cntot_u_ba_diff(1)
      cntot_u_ba_diff(1) = 0.D0
      cmtot_u_diff(2, 3) = cmtot_u_diff(2, 3) - dir*cmtot_u_ba_diff(3)
      cmtot_u_ba_diff(3) = 0.D0
      cmtot_u_diff(2, 2) = cmtot_u_diff(2, 2) - cmtot_u_ba_diff(2)
      cmtot_u_ba_diff(2) = 0.D0
      cmtot_u_diff(2, 1) = cmtot_u_diff(2, 1) - dir*cmtot_u_ba_diff(1)
      cmtot_u_ba_diff(1) = 0.D0
      cmtot_u_diff(1, 3) = cmtot_u_diff(1, 3) - crtot_u_ba_diff(3)
      crtot_u_ba_diff(3) = 0.D0
      cmtot_u_diff(1, 2) = cmtot_u_diff(1, 2) - dir*crtot_u_ba_diff(2)
      crtot_u_ba_diff(2) = 0.D0
      cmtot_u_diff(1, 1) = cmtot_u_diff(1, 1) - crtot_u_ba_diff(1)
      crtot_u_ba_diff(1) = 0.D0
      cftot_u_diff(3, 3) = cftot_u_diff(3, 3) - cztot_u_ba_diff(3)
      cztot_u_ba_diff(3) = 0.D0
      cftot_u_diff(3, 2) = cftot_u_diff(3, 2) - dir*cztot_u_ba_diff(2)
      cztot_u_ba_diff(2) = 0.D0
      cftot_u_diff(3, 1) = cftot_u_diff(3, 1) - cztot_u_ba_diff(1)
      cztot_u_ba_diff(1) = 0.D0
      cftot_u_diff(2, 3) = cftot_u_diff(2, 3) - dir*cytot_u_ba_diff(3)
      cytot_u_ba_diff(3) = 0.D0
      cftot_u_diff(2, 2) = cftot_u_diff(2, 2) - cytot_u_ba_diff(2)
      cytot_u_ba_diff(2) = 0.D0
      cftot_u_diff(2, 1) = cftot_u_diff(2, 1) - dir*cytot_u_ba_diff(1)
      cytot_u_ba_diff(1) = 0.D0
      cftot_u_diff(1, 3) = cftot_u_diff(1, 3) - cxtot_u_ba_diff(3)
      cxtot_u_ba_diff(3) = 0.D0
      cftot_u_diff(1, 2) = cftot_u_diff(1, 2) - dir*cxtot_u_ba_diff(2)
      cxtot_u_ba_diff(2) = 0.D0
      cftot_u_diff(1, 1) = cftot_u_diff(1, 1) - cxtot_u_ba_diff(1)
      cxtot_u_ba_diff(1) = 0.D0
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        cntot_be_diff = cntot_be_diff + rr_diff/abs2
        abs2_diff = -(cntot_be*rr_diff/abs2**2)
        CALL POPCONTROL1B(branch)
        IF (branch .EQ. 0) THEN
          crtot_be_diff = crtot_be_diff + abs2_diff
        ELSE
          crtot_be_diff = crtot_be_diff - abs2_diff
        END IF
        rr_diff = 0.D0
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .NE. 0) THEN
        temp_diff = bb_diff/(crtot_rz*cntot_be)
        crtot_be_diff = crtot_be_diff + cntot_rz*temp_diff
        cntot_rz_diff = cntot_rz_diff + crtot_be*temp_diff
        temp_diff0 = -(crtot_be*cntot_rz*temp_diff/(crtot_rz*cntot_be))
        crtot_rz_diff = crtot_rz_diff + cntot_be*temp_diff0
        cntot_be_diff = cntot_be_diff + crtot_rz*temp_diff0
        bb_diff = 0.D0
      END IF
      CALL POPCONTROL1B(branch)
      IF (branch .EQ. 0) THEN
        DO ii1=1,3
          xyzref_diff(ii1) = 0.D0
        ENDDO
      ELSE
        DO ii1=1,3
          xyzref_diff(ii1) = 0.D0
        ENDDO
        xyzref_diff(1) = xyzref_diff(1) + xnp_diff
        cref_diff = cref_diff + sm*xnp_diff
        sm_diff = sm_diff + cref*xnp_diff
        cmtot_al_diff = cmtot_al_diff - sm_diff/cltot_al
        cltot_al_diff = cltot_al_diff + cmtot_al*sm_diff/cltot_al**2
        xnp_diff = 0.D0
        sm_diff = 0.D0
      END IF
      CALL POPREAL8(cntot_rz)
      temp_diff = dir*2.0*cntot_rz_diff/bref
      cntot_rz_diff = temp_diff
      bref_diff = bref_diff - cntot_rz*temp_diff/bref
      temp_diff = dir*2.0*cntot_ry_diff/cref
      cntot_ry_diff = temp_diff
      cref_diff = cref_diff - cntot_ry*temp_diff/cref
      temp_diff = dir*2.0*cntot_rx_diff/bref
      cntot_rx_diff = temp_diff
      bref_diff = bref_diff - cntot_rx*temp_diff/bref
      temp_diff = 2.0*cmtot_rz_diff/bref
      cmtot_rz_diff = temp_diff
      bref_diff = bref_diff - cmtot_rz*temp_diff/bref
      temp_diff = 2.0*cmtot_ry_diff/cref
      cmtot_ry_diff = temp_diff
      cref_diff = cref_diff - cmtot_ry*temp_diff/cref
      temp_diff = 2.0*cmtot_rx_diff/bref
      cmtot_rx_diff = temp_diff
      bref_diff = bref_diff - cmtot_rx*temp_diff/bref
      CALL POPREAL8(crtot_rz)
      temp_diff = dir*2.0*crtot_rz_diff/bref
      crtot_rz_diff = temp_diff
      bref_diff = bref_diff - crtot_rz*temp_diff/bref
      temp_diff = dir*2.0*crtot_ry_diff/cref
      crtot_ry_diff = temp_diff
      cref_diff = cref_diff - crtot_ry*temp_diff/cref
      temp_diff = dir*2.0*crtot_rx_diff/bref
      crtot_rx_diff = temp_diff
      bref_diff = bref_diff - crtot_rx*temp_diff/bref
      temp_diff = 2.0*cdtot_rz_diff/bref
      cdtot_rz_diff = temp_diff
      bref_diff = bref_diff - cdtot_rz*temp_diff/bref
      temp_diff = 2.0*cdtot_ry_diff/cref
      cdtot_ry_diff = temp_diff
      cref_diff = cref_diff - cdtot_ry*temp_diff/cref
      temp_diff = 2.0*cdtot_rx_diff/bref
      cdtot_rx_diff = temp_diff
      bref_diff = bref_diff - cdtot_rx*temp_diff/bref
      temp_diff = 2.0*cytot_rz_diff/bref
      cytot_rz_diff = temp_diff
      bref_diff = bref_diff - cytot_rz*temp_diff/bref
      temp_diff = 2.0*cytot_ry_diff/cref
      cytot_ry_diff = temp_diff
      cref_diff = cref_diff - cytot_ry*temp_diff/cref
      temp_diff = 2.0*cytot_rx_diff/bref
      cytot_rx_diff = temp_diff
      bref_diff = bref_diff - cytot_rx*temp_diff/bref
      temp_diff = 2.0*cltot_rz_diff/bref
      cltot_rz_diff = temp_diff
      bref_diff = bref_diff - cltot_rz*temp_diff/bref
      temp_diff = 2.0*cltot_ry_diff/cref
      cltot_ry_diff = temp_diff
      cref_diff = cref_diff - cltot_ry*temp_diff/cref
      temp_diff = 2.0*cltot_rx_diff/bref
      cltot_rx_diff = temp_diff
      bref_diff = bref_diff - cltot_rx*temp_diff/bref
      cntot_be_diff = dir*cntot_be_diff
      cntot_al_diff = dir*cntot_al_diff
      crtot_be_diff = dir*crtot_be_diff
      crtot_al_diff = dir*crtot_al_diff
      DO ii1=1,numax
        cnsax_u_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,3
        wrot_rz_diff(ii1) = 0.D0
      ENDDO
      cnsax_u_diff(6) = cnsax_u_diff(6) + wrot_rz(3)*cntot_rz_diff + 
     +  wrot_rx(3)*cntot_rx_diff + wrot_a(3)*cntot_al_diff
      wrot_rz_diff(3) = wrot_rz_diff(3) + cnsax_u(6)*cntot_rz_diff + 
     +  cmsax_u(6)*cmtot_rz_diff + crsax_u(6)*crtot_rz_diff + cdtot_u(6)
     +  *cdtot_rz_diff + cytot_u(6)*cytot_rz_diff + cltot_u(6)*
     +  cltot_rz_diff
      cnsax_u_diff(4) = cnsax_u_diff(4) + wrot_rz(1)*cntot_rz_diff + 
     +  wrot_rx(1)*cntot_rx_diff + wrot_a(1)*cntot_al_diff
      wrot_rz_diff(1) = wrot_rz_diff(1) + cnsax_u(4)*cntot_rz_diff + 
     +  cmsax_u(4)*cmtot_rz_diff + crsax_u(4)*crtot_rz_diff + cdtot_u(4)
     +  *cdtot_rz_diff + cytot_u(4)*cytot_rz_diff + cltot_u(4)*
     +  cltot_rz_diff
      cnsax_u_diff(5) = cnsax_u_diff(5) + cntot_ry_diff + wrot_a(2)*
     +  cntot_al_diff
      DO ii1=1,3
        wrot_rx_diff(ii1) = 0.D0
      ENDDO
      wrot_rx_diff(1) = wrot_rx_diff(1) + cnsax_u(4)*cntot_rx_diff + 
     +  cmsax_u(4)*cmtot_rx_diff + crsax_u(4)*crtot_rx_diff + cdtot_u(4)
     +  *cdtot_rx_diff + cytot_u(4)*cytot_rx_diff + cltot_u(4)*
     +  cltot_rx_diff
      wrot_rx_diff(3) = wrot_rx_diff(3) + cnsax_u(6)*cntot_rx_diff + 
     +  cmsax_u(6)*cmtot_rx_diff + crsax_u(6)*crtot_rx_diff + cdtot_u(6)
     +  *cdtot_rx_diff + cytot_u(6)*cytot_rx_diff + cltot_u(6)*
     +  cltot_rx_diff
      DO ii1=1,3
        vinf_b_diff(ii1) = 0.D0
      ENDDO
      cnsax_u_diff(1) = cnsax_u_diff(1) + vinf_b(1)*cntot_be_diff + 
     +  vinf_a(1)*cntot_al_diff
      vinf_b_diff(1) = vinf_b_diff(1) + cnsax_u(1)*cntot_be_diff + 
     +  cmsax_u(1)*cmtot_be_diff + crsax_u(1)*crtot_be_diff + cdtot_u(1)
     +  *cdtot_be_diff + cytot_u(1)*cytot_be_diff + cltot_u(1)*
     +  cltot_be_diff
      cnsax_u_diff(2) = cnsax_u_diff(2) + vinf_b(2)*cntot_be_diff + 
     +  vinf_a(2)*cntot_al_diff
      vinf_b_diff(2) = vinf_b_diff(2) + cnsax_u(2)*cntot_be_diff + 
     +  cmsax_u(2)*cmtot_be_diff + crsax_u(2)*crtot_be_diff + cdtot_u(2)
     +  *cdtot_be_diff + cytot_u(2)*cytot_be_diff + cltot_u(2)*
     +  cltot_be_diff
      cnsax_u_diff(3) = cnsax_u_diff(3) + vinf_b(3)*cntot_be_diff + 
     +  vinf_a(3)*cntot_al_diff
      vinf_b_diff(3) = vinf_b_diff(3) + cnsax_u(3)*cntot_be_diff + 
     +  cmsax_u(3)*cmtot_be_diff + crsax_u(3)*crtot_be_diff + cdtot_u(3)
     +  *cdtot_be_diff + cytot_u(3)*cytot_be_diff + cltot_u(3)*
     +  cltot_be_diff
      DO ii1=1,3
        vinf_a_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,3
        wrot_a_diff(ii1) = 0.D0
      ENDDO
      vinf_a_diff(1) = vinf_a_diff(1) + cnsax_u(1)*cntot_al_diff + 
     +  cmsax_u(1)*cmtot_al_diff + crsax_u(1)*crtot_al_diff + cdtot_u(1)
     +  *cdtot_al_diff + cytot_u(1)*cytot_al_diff + cltot_u(1)*
     +  cltot_al_diff
      wrot_a_diff(1) = wrot_a_diff(1) + cnsax_u(4)*cntot_al_diff + 
     +  cmsax_u(4)*cmtot_al_diff + crsax_u(4)*crtot_al_diff + cdtot_u(4)
     +  *cdtot_al_diff + cytot_u(4)*cytot_al_diff + cltot_u(4)*
     +  cltot_al_diff
      vinf_a_diff(2) = vinf_a_diff(2) + cnsax_u(2)*cntot_al_diff + 
     +  cmsax_u(2)*cmtot_al_diff + crsax_u(2)*crtot_al_diff + cdtot_u(2)
     +  *cdtot_al_diff + cytot_u(2)*cytot_al_diff + cltot_u(2)*
     +  cltot_al_diff
      wrot_a_diff(2) = wrot_a_diff(2) + cnsax_u(5)*cntot_al_diff + 
     +  cmsax_u(5)*cmtot_al_diff + crsax_u(5)*crtot_al_diff + cdtot_u(5)
     +  *cdtot_al_diff + cytot_u(5)*cytot_al_diff + cltot_u(5)*
     +  cltot_al_diff
      vinf_a_diff(3) = vinf_a_diff(3) + cnsax_u(3)*cntot_al_diff + 
     +  cmsax_u(3)*cmtot_al_diff + crsax_u(3)*crtot_al_diff + cdtot_u(3)
     +  *cdtot_al_diff + cytot_u(3)*cytot_al_diff + cltot_u(3)*
     +  cltot_al_diff
      wrot_a_diff(3) = wrot_a_diff(3) + cnsax_u(6)*cntot_al_diff + 
     +  cmsax_u(6)*cmtot_al_diff + crsax_u(6)*crtot_al_diff + cdtot_u(6)
     +  *cdtot_al_diff + cytot_u(6)*cytot_al_diff + cltot_u(6)*
     +  cltot_al_diff
      cnsax_a_diff = cntot_al_diff
      DO ii1=1,numax
        cmsax_u_diff(ii1) = 0.D0
      ENDDO
      cmsax_u_diff(6) = cmsax_u_diff(6) + wrot_rz(3)*cmtot_rz_diff + 
     +  wrot_rx(3)*cmtot_rx_diff + wrot_a(3)*cmtot_al_diff
      cmsax_u_diff(4) = cmsax_u_diff(4) + wrot_rz(1)*cmtot_rz_diff + 
     +  wrot_rx(1)*cmtot_rx_diff + wrot_a(1)*cmtot_al_diff
      cmsax_u_diff(5) = cmsax_u_diff(5) + cmtot_ry_diff + wrot_a(2)*
     +  cmtot_al_diff
      cmsax_u_diff(1) = cmsax_u_diff(1) + vinf_b(1)*cmtot_be_diff + 
     +  vinf_a(1)*cmtot_al_diff
      cmsax_u_diff(2) = cmsax_u_diff(2) + vinf_b(2)*cmtot_be_diff + 
     +  vinf_a(2)*cmtot_al_diff
      cmsax_u_diff(3) = cmsax_u_diff(3) + vinf_b(3)*cmtot_be_diff + 
     +  vinf_a(3)*cmtot_al_diff
      DO ii1=1,numax
        crsax_u_diff(ii1) = 0.D0
      ENDDO
      crsax_u_diff(6) = crsax_u_diff(6) + wrot_rz(3)*crtot_rz_diff + 
     +  wrot_rx(3)*crtot_rx_diff + wrot_a(3)*crtot_al_diff
      crsax_u_diff(4) = crsax_u_diff(4) + wrot_rz(1)*crtot_rz_diff + 
     +  wrot_rx(1)*crtot_rx_diff + wrot_a(1)*crtot_al_diff
      crsax_u_diff(5) = crsax_u_diff(5) + crtot_ry_diff + wrot_a(2)*
     +  crtot_al_diff
      crsax_u_diff(1) = crsax_u_diff(1) + vinf_b(1)*crtot_be_diff + 
     +  vinf_a(1)*crtot_al_diff
      crsax_u_diff(2) = crsax_u_diff(2) + vinf_b(2)*crtot_be_diff + 
     +  vinf_a(2)*crtot_al_diff
      crsax_u_diff(3) = crsax_u_diff(3) + vinf_b(3)*crtot_be_diff + 
     +  vinf_a(3)*crtot_al_diff
      crsax_a_diff = crtot_al_diff
      DO ii1=1,numax
        cdtot_u_diff(ii1) = 0.D0
      ENDDO
      cdtot_u_diff(6) = cdtot_u_diff(6) + wrot_rz(3)*cdtot_rz_diff + 
     +  wrot_rx(3)*cdtot_rx_diff + wrot_a(3)*cdtot_al_diff
      cdtot_u_diff(4) = cdtot_u_diff(4) + wrot_rz(1)*cdtot_rz_diff + 
     +  wrot_rx(1)*cdtot_rx_diff + wrot_a(1)*cdtot_al_diff
      cdtot_u_diff(5) = cdtot_u_diff(5) + cdtot_ry_diff + wrot_a(2)*
     +  cdtot_al_diff
      cdtot_u_diff(1) = cdtot_u_diff(1) + vinf_b(1)*cdtot_be_diff + 
     +  vinf_a(1)*cdtot_al_diff
      cdtot_u_diff(2) = cdtot_u_diff(2) + vinf_b(2)*cdtot_be_diff + 
     +  vinf_a(2)*cdtot_al_diff
      cdtot_u_diff(3) = cdtot_u_diff(3) + vinf_b(3)*cdtot_be_diff + 
     +  vinf_a(3)*cdtot_al_diff
      cdtot_a_diff = cdtot_al_diff
      DO ii1=1,numax
        cytot_u_diff(ii1) = 0.D0
      ENDDO
      cytot_u_diff(6) = cytot_u_diff(6) + wrot_rz(3)*cytot_rz_diff + 
     +  wrot_rx(3)*cytot_rx_diff + wrot_a(3)*cytot_al_diff
      cytot_u_diff(4) = cytot_u_diff(4) + wrot_rz(1)*cytot_rz_diff + 
     +  wrot_rx(1)*cytot_rx_diff + wrot_a(1)*cytot_al_diff
      cytot_u_diff(5) = cytot_u_diff(5) + cytot_ry_diff + wrot_a(2)*
     +  cytot_al_diff
      cytot_u_diff(1) = cytot_u_diff(1) + vinf_b(1)*cytot_be_diff + 
     +  vinf_a(1)*cytot_al_diff
      cytot_u_diff(2) = cytot_u_diff(2) + vinf_b(2)*cytot_be_diff + 
     +  vinf_a(2)*cytot_al_diff
      cytot_u_diff(3) = cytot_u_diff(3) + vinf_b(3)*cytot_be_diff + 
     +  vinf_a(3)*cytot_al_diff
      DO ii1=1,numax
        cltot_u_diff(ii1) = 0.D0
      ENDDO
      cltot_u_diff(6) = cltot_u_diff(6) + wrot_rz(3)*cltot_rz_diff + 
     +  wrot_rx(3)*cltot_rx_diff + wrot_a(3)*cltot_al_diff
      cltot_u_diff(4) = cltot_u_diff(4) + wrot_rz(1)*cltot_rz_diff + 
     +  wrot_rx(1)*cltot_rx_diff + wrot_a(1)*cltot_al_diff
      cltot_u_diff(5) = cltot_u_diff(5) + cltot_ry_diff + wrot_a(2)*
     +  cltot_al_diff
      cltot_u_diff(1) = cltot_u_diff(1) + vinf_b(1)*cltot_be_diff + 
     +  vinf_a(1)*cltot_al_diff
      cltot_u_diff(2) = cltot_u_diff(2) + vinf_b(2)*cltot_be_diff + 
     +  vinf_a(2)*cltot_al_diff
      cltot_u_diff(3) = cltot_u_diff(3) + vinf_b(3)*cltot_be_diff + 
     +  vinf_a(3)*cltot_al_diff
      cltot_a_diff = cltot_al_diff
      sa_diff = 0.D0
      ca_diff = 0.D0
      DO k=ncontrol,1,-1
        temp_diff = dir*cnsax_d_diff(k)
        cnsax_d_diff(k) = 0.D0
        cmtot_d_diff(3, k) = cmtot_d_diff(3, k) + ca*temp_diff
        ca_diff = ca_diff + cmtot_d(3, k)*temp_diff
        cmtot_d_diff(1, k) = cmtot_d_diff(1, k) - sa*temp_diff
        sa_diff = sa_diff - cmtot_d(1, k)*temp_diff
        cmtot_d_diff(2, k) = cmtot_d_diff(2, k) + cmsax_d_diff(k)
        cmsax_d_diff(k) = 0.D0
        temp_diff = dir*crsax_d_diff(k)
        crsax_d_diff(k) = 0.D0
        cmtot_d_diff(1, k) = cmtot_d_diff(1, k) + ca*temp_diff
        ca_diff = ca_diff + cmtot_d(1, k)*temp_diff
        cmtot_d_diff(3, k) = cmtot_d_diff(3, k) + sa*temp_diff
        sa_diff = sa_diff + cmtot_d(3, k)*temp_diff
      ENDDO
      DO k=6,1,-1
        cmtot_u_diff(3, k) = cmtot_u_diff(3, k) + ca*cnsax_u_diff(k) + 
     +    sa*crsax_u_diff(k)
        ca_diff = ca_diff + cmtot_u(3, k)*cnsax_u_diff(k) + cmtot_u(1, k
     +    )*crsax_u_diff(k)
        cmtot_u_diff(1, k) = cmtot_u_diff(1, k) + ca*crsax_u_diff(k) - 
     +    sa*cnsax_u_diff(k)
        sa_diff = sa_diff + cmtot_u(3, k)*crsax_u_diff(k) - cmtot_u(1, k
     +    )*cnsax_u_diff(k)
        cnsax_u_diff(k) = 0.D0
        cmtot_u_diff(2, k) = cmtot_u_diff(2, k) + cmsax_u_diff(k)
        cmsax_u_diff(k) = 0.D0
        crsax_u_diff(k) = 0.D0
      ENDDO
      rz_diff = -(sa*wrot_a_diff(3)) - ca*wrot_a_diff(1)
      temp_diff = dir*rz_diff
      cmtot_diff(3) = cmtot_diff(3) + ca*crsax_a_diff - sa*cnsax_a_diff
      sa_diff = sa_diff + dir*wrot_rx_diff(3) - cmtot(3)*cnsax_a_diff - 
     +  cmtot(1)*crsax_a_diff - rz*wrot_a_diff(3) - rx*wrot_a_diff(1) - 
     +  dir*wrot_rz_diff(1) - wrot(1)*temp_diff
      cmtot_diff(1) = cmtot_diff(1) - ca*cnsax_a_diff - sa*crsax_a_diff
      ca_diff = ca_diff + cmtot(3)*crsax_a_diff - cmtot(1)*cnsax_a_diff 
     +  + rx*wrot_a_diff(3) + dir*wrot_rz_diff(3) - rz*wrot_a_diff(1) + 
     +  dir*wrot_rx_diff(1) + wrot(3)*temp_diff
      rx_diff = ca*wrot_a_diff(3) - sa*wrot_a_diff(1)
      wrot_a_diff(3) = 0.D0
      wrot_a_diff(2) = 0.D0
      wrot_rz_diff(3) = 0.D0
      wrot_rz_diff(2) = 0.D0
      wrot_rx_diff(3) = 0.D0
      wrot_rx_diff(2) = 0.D0
      DO ii1=1,3
        wrot_diff(ii1) = 0.D0
      ENDDO
      wrot_diff(3) = wrot_diff(3) + ca*temp_diff
      wrot_diff(1) = wrot_diff(1) - sa*temp_diff
      temp_diff = dir*rx_diff
      wrot_diff(1) = wrot_diff(1) + ca*temp_diff
      ca_diff = ca_diff + wrot(1)*temp_diff
      wrot_diff(3) = wrot_diff(3) + sa*temp_diff
      sa_diff = sa_diff + wrot(3)*temp_diff
      alfa_diff = COS(alfa)*sa_diff - SIN(alfa)*ca_diff
C
C
C        WRITE(*,8401) XNP
 8401 FORMAT(/'Neutral point  Xnp =',f11.6)
      END

C  Differentiation of get_res in reverse (adjoint) mode (with options i4 dr8 r8):
C   gradient     of useful results: wv_gam alfa beta vinf vinf_a
C                vinf_b wrot delcon xyzref mach cdref rv1 rv2 rv
C                rc gam gam_u gam_d src src_u res res_u res_d
C   with respect to varying inputs: wv_gam ysym zsym alfa beta
C                vinf vinf_a vinf_b wrot parval conval delcon xyzref
C                mach cdref rv1 rv2 rv rc rl chordv enc enc_d gam
C                gam_u gam_d src src_u res res_u res_d
C   RW status of diff variables: wv_gam:in-out ysym:out zsym:out
C                alfa:in-out beta:in-out vinf:in-out vinf_a:in-out
C                vinf_b:in-out wrot:in-out parval:out conval:out
C                delcon:in-out xyzref:in-out mach:in-zero cdref:in-zero
C                rv1:incr rv2:incr rv:incr rc:incr rl:out chordv:out
C                enc:out enc_d:out gam:incr gam_u:incr gam_d:incr
C                src:in-out src_u:in-out res:in-zero res_u:in-out
C                res_d:in-out
Csubroutine exec_rhs
C
C
C ======================== res and Adjoint for GAM ========      
      SUBROUTINE GET_RES_B()
      use avl_heap_inc
      use avl_heap_diff_inc
C
      INCLUDE 'AVL.INC'
      INCLUDE 'AVL_ad_seeds.inc'
      INTEGER i, ic
      REAL rhs_d(nvor)
      REAL rhs_d_diff(nvor)
      REAL betm
      REAL betm_diff
      INTRINSIC SQRT
      INTEGER l
      INTEGER iu
      INTEGER ii1
      INTEGER*4 branch
      INTEGER ii2
      INTEGER ii3
C Do not use this routine in the sovler
C IF(.NOT.LAIC) THEN
C      CALL build_AIC
C end if
      CALL SET_PAR_AND_CONS(nitmax, irun)
C---  
      CALL PUSHREAL8ARRAY(wc_gam, avl_real*3*nvmax**2/8)
c           CALL BUILD_AIC() no need to build the AIC again because we assume analysis is run before
      amach = mach
      betm = SQRT(1.0 - amach**2)
C
      CALL SRDSET(betm, xyzref, iysym, nbody, lfrst, nlmax, numax, nl, 
     +            rl, radl, src_u, dbl_u)
C
      CALL VSRD(betm, iysym, ysym, izsym, zsym, srcore, nbody, lfrst, 
     +          nlmax, nl, rl, radl, numax, src_u, dbl_u, nvor, rc, 
     +          wcsrd_u, nvmax)
C
C---- set VINF() vector from initial ALFA,BETA
      CALL VINFAB()
      DO ic=1,ncontrol
C------ don't bother if this control variable is undefined
        IF (lcondef(ic)) THEN
          CALL PUSHCONTROL1B(1)
        ELSE
          CALL PUSHCONTROL1B(0)
        END IF
      ENDDO
      DO ii1=1,nvor
        DO ii2=1,nvor
          aicn_diff(ii2, ii1) = 0.D0
        ENDDO
      ENDDO
      DO ii1=1,ndmax
        DO ii2=1,nvor
          DO ii3=1,3
            enc_d_diff(ii3, ii2, ii1) = 0.D0
          ENDDO
        ENDDO
      ENDDO
      DO ii1=1,numax
        DO ii2=1,nvor
          DO ii3=1,3
            wcsrd_u_diff(ii3, ii2, ii1) = 0.D0
          ENDDO
        ENDDO
      ENDDO
      DO ii1=1,nvor
        rhs_d_diff(ii1) = 0.D0
      ENDDO
      DO ic=ncontrol,1,-1
        CALL POPCONTROL1B(branch)
        IF (branch .NE. 0) THEN
          DO i=nvor,1,-1
            rhs_d_diff(i) = rhs_d_diff(i) - res_d_diff(i, ic)
          ENDDO
          CALL SET_GAM_D_RHS_B(ic, enc_d, enc_d_diff, rhs_d, rhs_d_diff)
          CALL MAT_PROD_B(aicn, aicn_diff, gam_d(:, ic), gam_d_diff(:, 
     +                    ic), nvor, res_d(:, ic), res_d_diff(:, ic))
          DO ii1=1,nvor
            res_d_diff(ii1, ic) = 0.D0
          ENDDO
        END IF
      ENDDO
      DO ii1=1,nvor
        rhs_diff(ii1) = 0.D0
      ENDDO
      DO i=nvor,1,-1
        rhs_diff(i) = rhs_diff(i) - res_diff(i)
      ENDDO
      CALL MAT_PROD_B(aicn, aicn_diff, gam, gam_diff, nvor, res, 
     +                res_diff)
      DO ii1=1,nvor
        res_diff(ii1) = 0.D0
      ENDDO
      CALL SET_VEL_RHS_B()
      DO ii1=1,numax
        DO ii2=1,nvor
          rhs_u_diff(ii2, ii1) = 0.D0
        ENDDO
      ENDDO
      DO iu=6,1,-1
        DO i=nvor,1,-1
          rhs_u_diff(i, iu) = rhs_u_diff(i, iu) - res_u_diff(i, iu)
        ENDDO
        CALL SET_VEL_RHS_U_B(iu)
        CALL MAT_PROD_B(aicn, aicn_diff, gam_u(:, iu), gam_u_diff(:, iu)
     +                  , nvor, res_u(:, iu), res_u_diff(:, iu))
        DO ii1=1,nvor
          res_u_diff(ii1, iu) = 0.D0
        ENDDO
      ENDDO
      DO l=nlnode,1,-1
        src_u_diff(l, 1) = src_u_diff(l, 1) + vinf(1)*src_diff(l)
        vinf_diff(1) = vinf_diff(1) + src_u(l, 1)*src_diff(l)
        src_u_diff(l, 2) = src_u_diff(l, 2) + vinf(2)*src_diff(l)
        vinf_diff(2) = vinf_diff(2) + src_u(l, 2)*src_diff(l)
        src_u_diff(l, 3) = src_u_diff(l, 3) + vinf(3)*src_diff(l)
        vinf_diff(3) = vinf_diff(3) + src_u(l, 3)*src_diff(l)
        src_u_diff(l, 4) = src_u_diff(l, 4) + wrot(1)*src_diff(l)
        wrot_diff(1) = wrot_diff(1) + src_u(l, 4)*src_diff(l)
        src_u_diff(l, 5) = src_u_diff(l, 5) + wrot(2)*src_diff(l)
        wrot_diff(2) = wrot_diff(2) + src_u(l, 5)*src_diff(l)
        src_u_diff(l, 6) = src_u_diff(l, 6) + wrot(3)*src_diff(l)
        wrot_diff(3) = wrot_diff(3) + src_u(l, 6)*src_diff(l)
        src_diff(l) = 0.D0
      ENDDO
      CALL VINFAB_B()
      CALL VSRD_B(betm, betm_diff, iysym, ysym, ysym_diff, izsym, zsym, 
     +            zsym_diff, srcore, nbody, lfrst, nlmax, nl, rl, 
     +            rl_diff, radl, numax, src_u, src_u_diff, dbl_u, 
     +            dbl_u_diff, nvor, rc, rc_diff, wcsrd_u, wcsrd_u_diff, 
     +            nvmax)
      CALL SRDSET_B(betm, betm_diff, xyzref, xyzref_diff, iysym, nbody, 
     +              lfrst, nlmax, numax, nl, rl, rl_diff, radl, src_u, 
     +              src_u_diff, dbl_u, dbl_u_diff)
      DO ii1=1,nvor
        chordv_diff(ii1) = 0.D0
      ENDDO
      CALL VVOR_B(betm, betm_diff, iysym, ysym, ysym_diff, izsym, zsym, 
     +            zsym_diff, vrcorec, vrcorew, nvor, rv1, rv1_diff, rv2
     +            , rv2_diff, lvcomp, chordv, chordv_diff, nvor, rv, 
     +            rv_diff, lvcomp, .true., wv_gam, wv_gam_diff, nvor)
      IF (1.0 - amach**2 .EQ. 0.D0) THEN
        amach_diff = 0.D0
      ELSE
        amach_diff = -(2*amach*betm_diff/(2.0*SQRT(1.0-amach**2)))
      END IF
      mach_diff = mach_diff + amach_diff
      CALL POPREAL8ARRAY(wc_gam, avl_real*3*nvmax**2/8)
      CALL BUILD_AIC_B()
      CALL SET_PAR_AND_CONS_B(nitmax, irun)
      mach_diff = 0.D0
      cdref_diff = 0.D0
      END

