C        Generated by TAPENADE     (INRIA, Ecuador team)
C  Tapenade 3.16 (develop) - 22 Aug 2023 15:51
C
C  Differentiation of calc_stab_derivs in forward (tangent) mode (with options i4 dr8 r8):
C   variations   of useful results: cxtot_u_ba cytot_u_ba cztot_u_ba
C                cxtot_d_ba cytot_d_ba cztot_d_ba crsax_d cmsax_d
C                cnsax_d crtot_u_ba cmtot_u_ba cntot_u_ba crtot_d_ba
C                cmtot_d_ba cntot_d_ba cdtot_al cltot_al cytot_al
C                crtot_al cmtot_al cntot_al cdtot_be cltot_be cytot_be
C                crtot_be cmtot_be cntot_be cdtot_rx cltot_rx cytot_rx
C                crtot_rx cmtot_rx cntot_rx cdtot_ry cltot_ry cytot_ry
C                crtot_ry cmtot_ry cntot_ry cdtot_rz cltot_rz cytot_rz
C                crtot_rz cmtot_rz cntot_rz xnp sm bb rr
C   with respect to varying inputs: alfa vinf_a vinf_b wrot cref
C                bref xyzref cdtot_a cltot_a cdtot_u cytot_u cltot_u
C                cftot_u cftot_d cmtot cmtot_u cmtot_d
C GETFILE
C
C
C
C ==================== addition wrapper helper programs ==============
C
      SUBROUTINE CALC_STAB_DERIVS_D()
      INCLUDE 'AVL.INC'
      INCLUDE 'AVL_ad_seeds.inc'
      CHARACTER*50 satype
      REAL wrot_rx(3), wrot_rz(3), wrot_a(3)
      REAL wrot_rx_diff(3), wrot_rz_diff(3), wrot_a_diff(3)
      REAL crsax_u(numax), cmsax_u(numax), cnsax_u(numax), crsax_g(ngmax
     +     ), cmsax_g(ngmax), cnsax_g(ngmax)
      REAL crsax_u_diff(numax), cmsax_u_diff(numax), cnsax_u_diff(numax)
      REAL dir
      EXTERNAL GETSA
      REAL ca
      REAL ca_diff
      INTRINSIC COS
      REAL sa
      REAL sa_diff
      INTRINSIC SIN
      REAL rx
      REAL rx_diff
      REAL ry
      REAL rz
      REAL rz_diff
      REAL crsax_a
      REAL crsax_a_diff
      REAL cnsax_a
      REAL cnsax_a_diff
      INTEGER k
      INTRINSIC ABS
      REAL(kind=avl_real) abs0
      REAL(kind=avl_real) abs1
      REAL(kind=avl_real) abs2
      REAL(kind=avl_real) abs2_diff
      INTEGER ii1
      REAL(kind=avl_real) temp
C
C CALL VINFAB
C CALL AERO
      CALL GETSA(lnasa_sa, satype, dir)
C
C---- set freestream velocity components from alpha, beta
C
C---- calculate forces and sensitivities
C
C---- set stability-axes rates (RX,RY,RZ) in terms of body-axes rates
      ca_diff = -(SIN(alfa)*alfa_diff)
      ca = COS(alfa)
      sa_diff = COS(alfa)*alfa_diff
      sa = SIN(alfa)
C
      rx_diff = dir*(ca*wrot_diff(1)+wrot(1)*ca_diff+sa*wrot_diff(3)+
     +  wrot(3)*sa_diff)
      rx = (wrot(1)*ca+wrot(3)*sa)*dir
      ry = wrot(2)
      rz_diff = dir*(ca*wrot_diff(3)+wrot(3)*ca_diff-sa*wrot_diff(1)-
     +  wrot(1)*sa_diff)
      rz = (wrot(3)*ca-wrot(1)*sa)*dir
C
C---- now vice-versa, and set sensitivities (which is what's really needed)
Cc    WROT(1)    =  RX*CA - RZ*SA
Cc    WROT(2)    =  RY
Cc    WROT(3)    =  RZ*CA + RX*SA
C
      DO ii1=1,3
        wrot_rx_diff(ii1) = 0.D0
      ENDDO
      wrot_rx_diff(1) = dir*ca_diff
      wrot_rx(1) = ca*dir
      wrot_rx_diff(2) = 0.D0
      wrot_rx(2) = 0.
      wrot_rx_diff(3) = dir*sa_diff
      wrot_rx(3) = sa*dir
C
      DO ii1=1,3
        wrot_rz_diff(ii1) = 0.D0
      ENDDO
      wrot_rz_diff(1) = -(dir*sa_diff)
      wrot_rz(1) = -(sa*dir)
      wrot_rz_diff(2) = 0.D0
      wrot_rz(2) = 0.
      wrot_rz_diff(3) = dir*ca_diff
      wrot_rz(3) = ca*dir
C
C!! = -WROT(3)
      DO ii1=1,3
        wrot_a_diff(ii1) = 0.D0
      ENDDO
      wrot_a_diff(1) = -(sa*rx_diff) - rx*sa_diff - ca*rz_diff - rz*
     +  ca_diff
      wrot_a(1) = -(rx*sa) - rz*ca
      wrot_a_diff(2) = 0.D0
      wrot_a(2) = 0.
C!! =  WROT(1)
      wrot_a_diff(3) = ca*rx_diff + rx*ca_diff - sa*rz_diff - rz*sa_diff
      wrot_a(3) = -(rz*sa) + rx*ca
C
C
      crsax_a_diff = ca*cmtot_diff(3) + cmtot(3)*ca_diff - sa*cmtot_diff
     +  (1) - cmtot(1)*sa_diff
      crsax_a = -(cmtot(1)*sa) + cmtot(3)*ca
      cnsax_a_diff = -(sa*cmtot_diff(3)) - cmtot(3)*sa_diff - ca*
     +  cmtot_diff(1) - cmtot(1)*ca_diff
      cnsax_a = -(cmtot(3)*sa) - cmtot(1)*ca
      DO ii1=1,numax
        cnsax_u_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,numax
        crsax_u_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,numax
        cmsax_u_diff(ii1) = 0.D0
      ENDDO
C
      DO k=1,6
        crsax_u_diff(k) = ca*cmtot_u_diff(1, k) + cmtot_u(1, k)*ca_diff 
     +    + sa*cmtot_u_diff(3, k) + cmtot_u(3, k)*sa_diff
        crsax_u(k) = cmtot_u(1, k)*ca + cmtot_u(3, k)*sa
        cmsax_u_diff(k) = cmtot_u_diff(2, k)
        cmsax_u(k) = cmtot_u(2, k)
        cnsax_u_diff(k) = ca*cmtot_u_diff(3, k) + cmtot_u(3, k)*ca_diff 
     +    - sa*cmtot_u_diff(1, k) - cmtot_u(1, k)*sa_diff
        cnsax_u(k) = cmtot_u(3, k)*ca - cmtot_u(1, k)*sa
      ENDDO
      DO ii1=1,ndmax
        crsax_d_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,ndmax
        cmsax_d_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,ndmax
        cnsax_d_diff(ii1) = 0.D0
      ENDDO
      DO k=1,ncontrol
        crsax_d_diff(k) = dir*(ca*cmtot_d_diff(1, k)+cmtot_d(1, k)*
     +    ca_diff+sa*cmtot_d_diff(3, k)+cmtot_d(3, k)*sa_diff)
        crsax_d(k) = dir*(cmtot_d(1, k)*ca+cmtot_d(3, k)*sa)
        cmsax_d_diff(k) = cmtot_d_diff(2, k)
        cmsax_d(k) = cmtot_d(2, k)
        cnsax_d_diff(k) = dir*(ca*cmtot_d_diff(3, k)+cmtot_d(3, k)*
     +    ca_diff-sa*cmtot_d_diff(1, k)-cmtot_d(1, k)*sa_diff)
        cnsax_d(k) = dir*(cmtot_d(3, k)*ca-cmtot_d(1, k)*sa)
      ENDDO
C
      DO k=1,ndesign
        crsax_g(k) = cmtot_g(1, k)*ca + cmtot_g(3, k)*sa
        cmsax_g(k) = cmtot_g(2, k)
        cnsax_g(k) = cmtot_g(3, k)*ca - cmtot_g(1, k)*sa
      ENDDO
C
C
C---- set force derivatives in stability axes
      cltot_al_diff = vinf_a(1)*cltot_u_diff(1) + cltot_u(1)*vinf_a_diff
     +  (1) + wrot_a(1)*cltot_u_diff(4) + cltot_u(4)*wrot_a_diff(1) + 
     +  vinf_a(2)*cltot_u_diff(2) + cltot_u(2)*vinf_a_diff(2) + wrot_a(2
     +  )*cltot_u_diff(5) + cltot_u(5)*wrot_a_diff(2) + vinf_a(3)*
     +  cltot_u_diff(3) + cltot_u(3)*vinf_a_diff(3) + wrot_a(3)*
     +  cltot_u_diff(6) + cltot_u(6)*wrot_a_diff(3) + cltot_a_diff
      cltot_al = cltot_u(1)*vinf_a(1) + cltot_u(4)*wrot_a(1) + cltot_u(2
     +  )*vinf_a(2) + cltot_u(5)*wrot_a(2) + cltot_u(3)*vinf_a(3) + 
     +  cltot_u(6)*wrot_a(3) + cltot_a
      cltot_be_diff = vinf_b(1)*cltot_u_diff(1) + cltot_u(1)*vinf_b_diff
     +  (1) + vinf_b(2)*cltot_u_diff(2) + cltot_u(2)*vinf_b_diff(2) + 
     +  vinf_b(3)*cltot_u_diff(3) + cltot_u(3)*vinf_b_diff(3)
      cltot_be = cltot_u(1)*vinf_b(1) + cltot_u(2)*vinf_b(2) + cltot_u(3
     +  )*vinf_b(3)
      cltot_rx_diff = wrot_rx(1)*cltot_u_diff(4) + cltot_u(4)*
     +  wrot_rx_diff(1) + wrot_rx(3)*cltot_u_diff(6) + cltot_u(6)*
     +  wrot_rx_diff(3)
      cltot_rx = cltot_u(4)*wrot_rx(1) + cltot_u(6)*wrot_rx(3)
      cltot_ry_diff = cltot_u_diff(5)
      cltot_ry = cltot_u(5)
      cltot_rz_diff = wrot_rz(3)*cltot_u_diff(6) + cltot_u(6)*
     +  wrot_rz_diff(3) + wrot_rz(1)*cltot_u_diff(4) + cltot_u(4)*
     +  wrot_rz_diff(1)
      cltot_rz = cltot_u(6)*wrot_rz(3) + cltot_u(4)*wrot_rz(1)
C
      cytot_al_diff = vinf_a(1)*cytot_u_diff(1) + cytot_u(1)*vinf_a_diff
     +  (1) + wrot_a(1)*cytot_u_diff(4) + cytot_u(4)*wrot_a_diff(1) + 
     +  vinf_a(2)*cytot_u_diff(2) + cytot_u(2)*vinf_a_diff(2) + wrot_a(2
     +  )*cytot_u_diff(5) + cytot_u(5)*wrot_a_diff(2) + vinf_a(3)*
     +  cytot_u_diff(3) + cytot_u(3)*vinf_a_diff(3) + wrot_a(3)*
     +  cytot_u_diff(6) + cytot_u(6)*wrot_a_diff(3)
      cytot_al = cytot_u(1)*vinf_a(1) + cytot_u(4)*wrot_a(1) + cytot_u(2
     +  )*vinf_a(2) + cytot_u(5)*wrot_a(2) + cytot_u(3)*vinf_a(3) + 
     +  cytot_u(6)*wrot_a(3)
      cytot_be_diff = vinf_b(1)*cytot_u_diff(1) + cytot_u(1)*vinf_b_diff
     +  (1) + vinf_b(2)*cytot_u_diff(2) + cytot_u(2)*vinf_b_diff(2) + 
     +  vinf_b(3)*cytot_u_diff(3) + cytot_u(3)*vinf_b_diff(3)
      cytot_be = cytot_u(1)*vinf_b(1) + cytot_u(2)*vinf_b(2) + cytot_u(3
     +  )*vinf_b(3)
      cytot_rx_diff = wrot_rx(1)*cytot_u_diff(4) + cytot_u(4)*
     +  wrot_rx_diff(1) + wrot_rx(3)*cytot_u_diff(6) + cytot_u(6)*
     +  wrot_rx_diff(3)
      cytot_rx = cytot_u(4)*wrot_rx(1) + cytot_u(6)*wrot_rx(3)
      cytot_ry_diff = cytot_u_diff(5)
      cytot_ry = cytot_u(5)
      cytot_rz_diff = wrot_rz(3)*cytot_u_diff(6) + cytot_u(6)*
     +  wrot_rz_diff(3) + wrot_rz(1)*cytot_u_diff(4) + cytot_u(4)*
     +  wrot_rz_diff(1)
      cytot_rz = cytot_u(6)*wrot_rz(3) + cytot_u(4)*wrot_rz(1)
C
      cdtot_al_diff = vinf_a(1)*cdtot_u_diff(1) + cdtot_u(1)*vinf_a_diff
     +  (1) + wrot_a(1)*cdtot_u_diff(4) + cdtot_u(4)*wrot_a_diff(1) + 
     +  vinf_a(2)*cdtot_u_diff(2) + cdtot_u(2)*vinf_a_diff(2) + wrot_a(2
     +  )*cdtot_u_diff(5) + cdtot_u(5)*wrot_a_diff(2) + vinf_a(3)*
     +  cdtot_u_diff(3) + cdtot_u(3)*vinf_a_diff(3) + wrot_a(3)*
     +  cdtot_u_diff(6) + cdtot_u(6)*wrot_a_diff(3) + cdtot_a_diff
      cdtot_al = cdtot_u(1)*vinf_a(1) + cdtot_u(4)*wrot_a(1) + cdtot_u(2
     +  )*vinf_a(2) + cdtot_u(5)*wrot_a(2) + cdtot_u(3)*vinf_a(3) + 
     +  cdtot_u(6)*wrot_a(3) + cdtot_a
      cdtot_be_diff = vinf_b(1)*cdtot_u_diff(1) + cdtot_u(1)*vinf_b_diff
     +  (1) + vinf_b(2)*cdtot_u_diff(2) + cdtot_u(2)*vinf_b_diff(2) + 
     +  vinf_b(3)*cdtot_u_diff(3) + cdtot_u(3)*vinf_b_diff(3)
      cdtot_be = cdtot_u(1)*vinf_b(1) + cdtot_u(2)*vinf_b(2) + cdtot_u(3
     +  )*vinf_b(3)
      cdtot_rx_diff = wrot_rx(1)*cdtot_u_diff(4) + cdtot_u(4)*
     +  wrot_rx_diff(1) + wrot_rx(3)*cdtot_u_diff(6) + cdtot_u(6)*
     +  wrot_rx_diff(3)
      cdtot_rx = cdtot_u(4)*wrot_rx(1) + cdtot_u(6)*wrot_rx(3)
      cdtot_ry_diff = cdtot_u_diff(5)
      cdtot_ry = cdtot_u(5)
      cdtot_rz_diff = wrot_rz(3)*cdtot_u_diff(6) + cdtot_u(6)*
     +  wrot_rz_diff(3) + wrot_rz(1)*cdtot_u_diff(4) + cdtot_u(4)*
     +  wrot_rz_diff(1)
      cdtot_rz = cdtot_u(6)*wrot_rz(3) + cdtot_u(4)*wrot_rz(1)
C
      crtot_al_diff = vinf_a(1)*crsax_u_diff(1) + crsax_u(1)*vinf_a_diff
     +  (1) + wrot_a(1)*crsax_u_diff(4) + crsax_u(4)*wrot_a_diff(1) + 
     +  vinf_a(2)*crsax_u_diff(2) + crsax_u(2)*vinf_a_diff(2) + wrot_a(2
     +  )*crsax_u_diff(5) + crsax_u(5)*wrot_a_diff(2) + vinf_a(3)*
     +  crsax_u_diff(3) + crsax_u(3)*vinf_a_diff(3) + wrot_a(3)*
     +  crsax_u_diff(6) + crsax_u(6)*wrot_a_diff(3) + crsax_a_diff
      crtot_al = crsax_u(1)*vinf_a(1) + crsax_u(4)*wrot_a(1) + crsax_u(2
     +  )*vinf_a(2) + crsax_u(5)*wrot_a(2) + crsax_u(3)*vinf_a(3) + 
     +  crsax_u(6)*wrot_a(3) + crsax_a
      crtot_be_diff = vinf_b(1)*crsax_u_diff(1) + crsax_u(1)*vinf_b_diff
     +  (1) + vinf_b(2)*crsax_u_diff(2) + crsax_u(2)*vinf_b_diff(2) + 
     +  vinf_b(3)*crsax_u_diff(3) + crsax_u(3)*vinf_b_diff(3)
      crtot_be = crsax_u(1)*vinf_b(1) + crsax_u(2)*vinf_b(2) + crsax_u(3
     +  )*vinf_b(3)
      crtot_rx_diff = wrot_rx(1)*crsax_u_diff(4) + crsax_u(4)*
     +  wrot_rx_diff(1) + wrot_rx(3)*crsax_u_diff(6) + crsax_u(6)*
     +  wrot_rx_diff(3)
      crtot_rx = crsax_u(4)*wrot_rx(1) + crsax_u(6)*wrot_rx(3)
      crtot_ry_diff = crsax_u_diff(5)
      crtot_ry = crsax_u(5)
      crtot_rz_diff = wrot_rz(3)*crsax_u_diff(6) + crsax_u(6)*
     +  wrot_rz_diff(3) + wrot_rz(1)*crsax_u_diff(4) + crsax_u(4)*
     +  wrot_rz_diff(1)
      crtot_rz = crsax_u(6)*wrot_rz(3) + crsax_u(4)*wrot_rz(1)
C
      cmtot_al_diff = vinf_a(1)*cmsax_u_diff(1) + cmsax_u(1)*vinf_a_diff
     +  (1) + wrot_a(1)*cmsax_u_diff(4) + cmsax_u(4)*wrot_a_diff(1) + 
     +  vinf_a(2)*cmsax_u_diff(2) + cmsax_u(2)*vinf_a_diff(2) + wrot_a(2
     +  )*cmsax_u_diff(5) + cmsax_u(5)*wrot_a_diff(2) + vinf_a(3)*
     +  cmsax_u_diff(3) + cmsax_u(3)*vinf_a_diff(3) + wrot_a(3)*
     +  cmsax_u_diff(6) + cmsax_u(6)*wrot_a_diff(3)
      cmtot_al = cmsax_u(1)*vinf_a(1) + cmsax_u(4)*wrot_a(1) + cmsax_u(2
     +  )*vinf_a(2) + cmsax_u(5)*wrot_a(2) + cmsax_u(3)*vinf_a(3) + 
     +  cmsax_u(6)*wrot_a(3)
      cmtot_be_diff = vinf_b(1)*cmsax_u_diff(1) + cmsax_u(1)*vinf_b_diff
     +  (1) + vinf_b(2)*cmsax_u_diff(2) + cmsax_u(2)*vinf_b_diff(2) + 
     +  vinf_b(3)*cmsax_u_diff(3) + cmsax_u(3)*vinf_b_diff(3)
      cmtot_be = cmsax_u(1)*vinf_b(1) + cmsax_u(2)*vinf_b(2) + cmsax_u(3
     +  )*vinf_b(3)
      cmtot_rx_diff = wrot_rx(1)*cmsax_u_diff(4) + cmsax_u(4)*
     +  wrot_rx_diff(1) + wrot_rx(3)*cmsax_u_diff(6) + cmsax_u(6)*
     +  wrot_rx_diff(3)
      cmtot_rx = cmsax_u(4)*wrot_rx(1) + cmsax_u(6)*wrot_rx(3)
      cmtot_ry_diff = cmsax_u_diff(5)
      cmtot_ry = cmsax_u(5)
      cmtot_rz_diff = wrot_rz(3)*cmsax_u_diff(6) + cmsax_u(6)*
     +  wrot_rz_diff(3) + wrot_rz(1)*cmsax_u_diff(4) + cmsax_u(4)*
     +  wrot_rz_diff(1)
      cmtot_rz = cmsax_u(6)*wrot_rz(3) + cmsax_u(4)*wrot_rz(1)
C
      cntot_al_diff = vinf_a(1)*cnsax_u_diff(1) + cnsax_u(1)*vinf_a_diff
     +  (1) + wrot_a(1)*cnsax_u_diff(4) + cnsax_u(4)*wrot_a_diff(1) + 
     +  vinf_a(2)*cnsax_u_diff(2) + cnsax_u(2)*vinf_a_diff(2) + wrot_a(2
     +  )*cnsax_u_diff(5) + cnsax_u(5)*wrot_a_diff(2) + vinf_a(3)*
     +  cnsax_u_diff(3) + cnsax_u(3)*vinf_a_diff(3) + wrot_a(3)*
     +  cnsax_u_diff(6) + cnsax_u(6)*wrot_a_diff(3) + cnsax_a_diff
      cntot_al = cnsax_u(1)*vinf_a(1) + cnsax_u(4)*wrot_a(1) + cnsax_u(2
     +  )*vinf_a(2) + cnsax_u(5)*wrot_a(2) + cnsax_u(3)*vinf_a(3) + 
     +  cnsax_u(6)*wrot_a(3) + cnsax_a
      cntot_be_diff = vinf_b(1)*cnsax_u_diff(1) + cnsax_u(1)*vinf_b_diff
     +  (1) + vinf_b(2)*cnsax_u_diff(2) + cnsax_u(2)*vinf_b_diff(2) + 
     +  vinf_b(3)*cnsax_u_diff(3) + cnsax_u(3)*vinf_b_diff(3)
      cntot_be = cnsax_u(1)*vinf_b(1) + cnsax_u(2)*vinf_b(2) + cnsax_u(3
     +  )*vinf_b(3)
      cntot_rx_diff = wrot_rx(1)*cnsax_u_diff(4) + cnsax_u(4)*
     +  wrot_rx_diff(1) + wrot_rx(3)*cnsax_u_diff(6) + cnsax_u(6)*
     +  wrot_rx_diff(3)
      cntot_rx = cnsax_u(4)*wrot_rx(1) + cnsax_u(6)*wrot_rx(3)
      cntot_ry_diff = cnsax_u_diff(5)
      cntot_ry = cnsax_u(5)
C apply the facotors to the outputs as done in the print statements of DERMATS
      cntot_rz_diff = wrot_rz(3)*cnsax_u_diff(6) + cnsax_u(6)*
     +  wrot_rz_diff(3) + wrot_rz(1)*cnsax_u_diff(4) + cnsax_u(4)*
     +  wrot_rz_diff(1)
      cntot_rz = cnsax_u(6)*wrot_rz(3) + cnsax_u(4)*wrot_rz(1)
C
C        
C
      crtot_al_diff = dir*crtot_al_diff
      crtot_al = dir*crtot_al
      crtot_be_diff = dir*crtot_be_diff
      crtot_be = dir*crtot_be
      cntot_al_diff = dir*cntot_al_diff
      cntot_al = dir*cntot_al
      cntot_be_diff = dir*cntot_be_diff
      cntot_be = dir*cntot_be
      cltot_rx_diff = 2.0*(cltot_rx_diff-cltot_rx*bref_diff/bref)/bref
      cltot_rx = cltot_rx*2.0/bref
      cltot_ry_diff = 2.0*(cltot_ry_diff-cltot_ry*cref_diff/cref)/cref
      cltot_ry = cltot_ry*2.0/cref
      cltot_rz_diff = 2.0*(cltot_rz_diff-cltot_rz*bref_diff/bref)/bref
      cltot_rz = cltot_rz*2.0/bref
C
      cytot_rx_diff = 2.0*(cytot_rx_diff-cytot_rx*bref_diff/bref)/bref
      cytot_rx = cytot_rx*2.0/bref
      cytot_ry_diff = 2.0*(cytot_ry_diff-cytot_ry*cref_diff/cref)/cref
      cytot_ry = cytot_ry*2.0/cref
      cytot_rz_diff = 2.0*(cytot_rz_diff-cytot_rz*bref_diff/bref)/bref
      cytot_rz = cytot_rz*2.0/bref
      cdtot_rx_diff = 2.0*(cdtot_rx_diff-cdtot_rx*bref_diff/bref)/bref
      cdtot_rx = cdtot_rx*2.0/bref
      cdtot_ry_diff = 2.0*(cdtot_ry_diff-cdtot_ry*cref_diff/cref)/cref
      cdtot_ry = cdtot_ry*2.0/cref
      cdtot_rz_diff = 2.0*(cdtot_rz_diff-cdtot_rz*bref_diff/bref)/bref
      cdtot_rz = cdtot_rz*2.0/bref
C
      crtot_rx_diff = dir*2.0*(crtot_rx_diff-crtot_rx*bref_diff/bref)/
     +  bref
      crtot_rx = dir*crtot_rx*2.0/bref
      crtot_ry_diff = dir*2.0*(crtot_ry_diff-crtot_ry*cref_diff/cref)/
     +  cref
      crtot_ry = dir*crtot_ry*2.0/cref
      crtot_rz_diff = dir*2.0*(crtot_rz_diff-crtot_rz*bref_diff/bref)/
     +  bref
      crtot_rz = dir*crtot_rz*2.0/bref
      cmtot_rx_diff = 2.0*(cmtot_rx_diff-cmtot_rx*bref_diff/bref)/bref
      cmtot_rx = cmtot_rx*2.0/bref
      cmtot_ry_diff = 2.0*(cmtot_ry_diff-cmtot_ry*cref_diff/cref)/cref
      cmtot_ry = cmtot_ry*2.0/cref
      cmtot_rz_diff = 2.0*(cmtot_rz_diff-cmtot_rz*bref_diff/bref)/bref
      cmtot_rz = cmtot_rz*2.0/bref
      cntot_rx_diff = dir*2.0*(cntot_rx_diff-cntot_rx*bref_diff/bref)/
     +  bref
      cntot_rx = dir*cntot_rx*2.0/bref
      cntot_ry_diff = dir*2.0*(cntot_ry_diff-cntot_ry*cref_diff/cref)/
     +  cref
      cntot_ry = dir*cntot_ry*2.0/cref
      cntot_rz_diff = dir*2.0*(cntot_rz_diff-cntot_rz*bref_diff/bref)/
     +  bref
      cntot_rz = dir*cntot_rz*2.0/bref
C
      IF (cltot_al .NE. 0.0) THEN
C  XNP = XYZREF(1) - CREF*CMTOT_AL/CLTOT_AL
C  SM = (XNP - XYZREF(1))/CREF This is the same as below
        sm_diff = -((cmtot_al_diff-cmtot_al*cltot_al_diff/cltot_al)/
     +    cltot_al)
        sm = -(cmtot_al/cltot_al)
        xnp_diff = xyzref_diff(1) + sm*cref_diff + cref*sm_diff
        xnp = xyzref(1) + cref*sm
      ELSE
        xnp_diff = 0.D0
        sm_diff = 0.D0
      END IF
      IF (crtot_rz*cntot_be .GE. 0.) THEN
        abs0 = crtot_rz*cntot_be
      ELSE
        abs0 = -(crtot_rz*cntot_be)
      END IF
C
      IF (abs0 .GT. 0.0) THEN
        temp = crtot_be*cntot_rz/(crtot_rz*cntot_be)
        bb_diff = (cntot_rz*crtot_be_diff+crtot_be*cntot_rz_diff-temp*(
     +    cntot_be*crtot_rz_diff+crtot_rz*cntot_be_diff))/(crtot_rz*
     +    cntot_be)
        bb = temp
C        WRITE(LU,8402) BB 
C  8402  FORMAT(/' Clb Cnr / Clr Cnb  =', F11.6,
C      &    '    (  > 1 if spirally stable )')
      ELSE
        bb_diff = 0.D0
      END IF
      IF (crtot_be .GE. 0.) THEN
        abs1 = crtot_be
      ELSE
        abs1 = -crtot_be
      END IF
C ---- body axis derivatives
C these expressions are taken from DERMATB
C'  axial   vel. u', ' sideslip vel. v', '  normal  vel. w'
      IF (abs1 .GT. 0.0) THEN
        IF (crtot_be .GE. 0.) THEN
          abs2_diff = crtot_be_diff
          abs2 = crtot_be
        ELSE
          abs2_diff = -crtot_be_diff
          abs2 = -crtot_be
        END IF
C this is the lateral stablity parameter suggested by John Yost
        rr_diff = (cntot_be_diff-cntot_be*abs2_diff/abs2)/abs2
        rr = cntot_be/abs2
      ELSE
        rr_diff = 0.D0
      END IF
      DO ii1=1,numax
        cxtot_u_ba_diff(ii1) = 0.D0
      ENDDO
      cxtot_u_ba_diff(1) = -cftot_u_diff(1, 1)
      cxtot_u_ba(1) = -cftot_u(1, 1)
      cxtot_u_ba_diff(2) = -(dir*cftot_u_diff(1, 2))
      cxtot_u_ba(2) = -(dir*cftot_u(1, 2))
      cxtot_u_ba_diff(3) = -cftot_u_diff(1, 3)
      cxtot_u_ba(3) = -cftot_u(1, 3)
      DO ii1=1,numax
        cytot_u_ba_diff(ii1) = 0.D0
      ENDDO
      cytot_u_ba_diff(1) = -(dir*cftot_u_diff(2, 1))
      cytot_u_ba(1) = -(dir*cftot_u(2, 1))
      cytot_u_ba_diff(2) = -cftot_u_diff(2, 2)
      cytot_u_ba(2) = -cftot_u(2, 2)
      cytot_u_ba_diff(3) = -(dir*cftot_u_diff(2, 3))
      cytot_u_ba(3) = -(dir*cftot_u(2, 3))
      DO ii1=1,numax
        cztot_u_ba_diff(ii1) = 0.D0
      ENDDO
      cztot_u_ba_diff(1) = -cftot_u_diff(3, 1)
      cztot_u_ba(1) = -cftot_u(3, 1)
      cztot_u_ba_diff(2) = -(dir*cftot_u_diff(3, 2))
      cztot_u_ba(2) = -(dir*cftot_u(3, 2))
      cztot_u_ba_diff(3) = -cftot_u_diff(3, 3)
      cztot_u_ba(3) = -cftot_u(3, 3)
      DO ii1=1,numax
        crtot_u_ba_diff(ii1) = 0.D0
      ENDDO
      crtot_u_ba_diff(1) = -cmtot_u_diff(1, 1)
      crtot_u_ba(1) = -cmtot_u(1, 1)
      crtot_u_ba_diff(2) = -(dir*cmtot_u_diff(1, 2))
      crtot_u_ba(2) = -(dir*cmtot_u(1, 2))
      crtot_u_ba_diff(3) = -cmtot_u_diff(1, 3)
      crtot_u_ba(3) = -cmtot_u(1, 3)
      DO ii1=1,numax
        cmtot_u_ba_diff(ii1) = 0.D0
      ENDDO
      cmtot_u_ba_diff(1) = -(dir*cmtot_u_diff(2, 1))
      cmtot_u_ba(1) = -(dir*cmtot_u(2, 1))
      cmtot_u_ba_diff(2) = -cmtot_u_diff(2, 2)
      cmtot_u_ba(2) = -cmtot_u(2, 2)
      cmtot_u_ba_diff(3) = -(dir*cmtot_u_diff(2, 3))
      cmtot_u_ba(3) = -(dir*cmtot_u(2, 3))
      DO ii1=1,numax
        cntot_u_ba_diff(ii1) = 0.D0
      ENDDO
      cntot_u_ba_diff(1) = -cmtot_u_diff(3, 1)
      cntot_u_ba(1) = -cmtot_u(3, 1)
      cntot_u_ba_diff(2) = -(dir*cmtot_u_diff(3, 2))
      cntot_u_ba(2) = -(dir*cmtot_u(3, 2))
C'    roll rate  p','   pitch rate  q','     yaw rate  r'
      cntot_u_ba_diff(3) = -cmtot_u_diff(3, 3)
      cntot_u_ba(3) = -cmtot_u(3, 3)
      temp = cftot_u(1, 4)/bref
      cxtot_u_ba_diff(4) = 2.0*(cftot_u_diff(1, 4)-temp*bref_diff)/bref
      cxtot_u_ba(4) = 2.0*temp
      temp = cftot_u(1, 5)/cref
      cxtot_u_ba_diff(5) = dir*2.0*(cftot_u_diff(1, 5)-temp*cref_diff)/
     +  cref
      cxtot_u_ba(5) = dir*2.0*temp
      temp = cftot_u(1, 6)/bref
      cxtot_u_ba_diff(6) = 2.0*(cftot_u_diff(1, 6)-temp*bref_diff)/bref
      cxtot_u_ba(6) = 2.0*temp
      temp = cftot_u(2, 4)/bref
      cytot_u_ba_diff(4) = dir*2.0*(cftot_u_diff(2, 4)-temp*bref_diff)/
     +  bref
      cytot_u_ba(4) = dir*2.0*temp
      temp = cftot_u(2, 5)/cref
      cytot_u_ba_diff(5) = 2.0*(cftot_u_diff(2, 5)-temp*cref_diff)/cref
      cytot_u_ba(5) = 2.0*temp
      temp = cftot_u(2, 6)/bref
      cytot_u_ba_diff(6) = dir*2.0*(cftot_u_diff(2, 6)-temp*bref_diff)/
     +  bref
      cytot_u_ba(6) = dir*2.0*temp
      temp = cftot_u(3, 4)/bref
      cztot_u_ba_diff(4) = 2.0*(cftot_u_diff(3, 4)-temp*bref_diff)/bref
      cztot_u_ba(4) = 2.0*temp
      temp = cftot_u(3, 5)/cref
      cztot_u_ba_diff(5) = dir*2.0*(cftot_u_diff(3, 5)-temp*cref_diff)/
     +  cref
      cztot_u_ba(5) = dir*2.0*temp
      temp = cftot_u(3, 6)/bref
      cztot_u_ba_diff(6) = 2.0*(cftot_u_diff(3, 6)-temp*bref_diff)/bref
      cztot_u_ba(6) = 2.0*temp
      temp = cmtot_u(1, 4)/bref
      crtot_u_ba_diff(4) = 2.0*(cmtot_u_diff(1, 4)-temp*bref_diff)/bref
      crtot_u_ba(4) = 2.0*temp
      temp = cmtot_u(1, 5)/cref
      crtot_u_ba_diff(5) = dir*2.0*(cmtot_u_diff(1, 5)-temp*cref_diff)/
     +  cref
      crtot_u_ba(5) = dir*2.0*temp
      temp = cmtot_u(1, 6)/bref
      crtot_u_ba_diff(6) = 2.0*(cmtot_u_diff(1, 6)-temp*bref_diff)/bref
      crtot_u_ba(6) = 2.0*temp
      temp = cmtot_u(2, 4)/bref
      cmtot_u_ba_diff(4) = dir*2.0*(cmtot_u_diff(2, 4)-temp*bref_diff)/
     +  bref
      cmtot_u_ba(4) = dir*2.0*temp
      temp = cmtot_u(2, 5)/cref
      cmtot_u_ba_diff(5) = 2.0*(cmtot_u_diff(2, 5)-temp*cref_diff)/cref
      cmtot_u_ba(5) = 2.0*temp
      temp = cmtot_u(2, 6)/bref
      cmtot_u_ba_diff(6) = dir*2.0*(cmtot_u_diff(2, 6)-temp*bref_diff)/
     +  bref
      cmtot_u_ba(6) = dir*2.0*temp
      temp = cmtot_u(3, 4)/bref
      cntot_u_ba_diff(4) = 2.0*(cmtot_u_diff(3, 4)-temp*bref_diff)/bref
      cntot_u_ba(4) = 2.0*temp
      temp = cmtot_u(3, 5)/cref
      cntot_u_ba_diff(5) = dir*2.0*(cmtot_u_diff(3, 5)-temp*cref_diff)/
     +  cref
      cntot_u_ba(5) = dir*2.0*temp
C control surfaces
      temp = cmtot_u(3, 6)/bref
      cntot_u_ba_diff(6) = 2.0*(cmtot_u_diff(3, 6)-temp*bref_diff)/bref
      cntot_u_ba(6) = 2.0*temp
      DO ii1=1,ndmax
        cxtot_d_ba_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,ndmax
        cytot_d_ba_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,ndmax
        cztot_d_ba_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,ndmax
        crtot_d_ba_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,ndmax
        cmtot_d_ba_diff(ii1) = 0.D0
      ENDDO
      DO ii1=1,ndmax
        cntot_d_ba_diff(ii1) = 0.D0
      ENDDO
      DO k=1,ncontrol
        cxtot_d_ba_diff(k) = dir*cftot_d_diff(1, k)
        cxtot_d_ba(k) = dir*cftot_d(1, k)
        cytot_d_ba_diff(k) = cftot_d_diff(2, k)
        cytot_d_ba(k) = cftot_d(2, k)
        cztot_d_ba_diff(k) = dir*cftot_d_diff(3, k)
        cztot_d_ba(k) = dir*cftot_d(3, k)
        crtot_d_ba_diff(k) = dir*cmtot_d_diff(1, k)
        crtot_d_ba(k) = dir*cmtot_d(1, k)
        cmtot_d_ba_diff(k) = cmtot_d_diff(2, k)
        cmtot_d_ba(k) = cmtot_d(2, k)
        cntot_d_ba_diff(k) = dir*cmtot_d_diff(3, k)
        cntot_d_ba(k) = dir*cmtot_d(3, k)
C design variables
      ENDDO
      DO k=1,ndesign
        cxtot_g_ba(k) = dir*cftot_g(1, k)
        cytot_g_ba(k) = cftot_g(2, k)
        cztot_g_ba(k) = dir*cftot_g(3, k)
        crtot_g_ba(k) = dir*cmtot_g(1, k)
        cmtot_g_ba(k) = cmtot_g(2, k)
        cntot_g_ba(k) = dir*cmtot_g(3, k)
      ENDDO
C C
      RETURN
C
C
C        WRITE(*,8401) XNP
 8401 FORMAT(/'Neutral point  Xnp =',f11.6)
      END

C  Differentiation of get_res in forward (tangent) mode (with options i4 dr8 r8):
C   variations   of useful results: wv_gam alfa beta vinf vinf_a
C                vinf_b wrot delcon xyzref mach cdref src src_u
C                res res_u res_d
C   with respect to varying inputs: ysym zsym parval conval xyzref
C                rv1 rv2 rv rc rl chordv enc enc_d gam gam_u gam_d
C   RW status of diff variables: wv_gam:out ysym:in zsym:in alfa:out
C                beta:out vinf:out vinf_a:out vinf_b:out wrot:out
C                parval:in conval:in delcon:out xyzref:in-out mach:out
C                cdref:out rv1:in rv2:in rv:in rc:in rl:in chordv:in
C                enc:in enc_d:in gam:in gam_u:in gam_d:in src:out
C                src_u:out res:out res_u:out res_d:out
Csubroutine exec_rhs
C
C
C ======================== res and Adjoint for GAM ========      
      SUBROUTINE GET_RES_D()
      use avl_heap_inc
      use avl_heap_diff_inc
      INCLUDE 'AVL.INC'
      INCLUDE 'AVL_ad_seeds.inc'
      INTEGER i, ic
      REAL rhs_d(nvor)
      REAL rhs_d_diff(nvor)
      REAL betm
      REAL betm_diff
      INTRINSIC SQRT
      INTEGER l
      INTEGER iu
      REAL(kind=avl_real) arg1
      REAL(kind=avl_real) arg1_diff
      REAL(kind=avl_real) temp
      INTEGER ii1
      INTEGER ii2
C Do not use this routine in the sovler
C IF(.NOT.LAIC) THEN
C      CALL build_AIC
C end if
      CALL SET_PAR_AND_CONS_D(nitmax, irun)
C---  
      CALL BUILD_AIC_D()
      amach_diff = mach_diff
      amach = mach
      arg1_diff = -(2*amach*amach_diff)
      arg1 = 1.0 - amach**2
      temp = SQRT(arg1)
      IF (arg1 .EQ. 0.D0) THEN
        betm_diff = 0.D0
      ELSE
        betm_diff = arg1_diff/(2.0*temp)
      END IF
      betm = temp
      CALL VVOR_D(betm, betm_diff, iysym, ysym, ysym_diff, izsym, zsym, 
     +            zsym_diff, vrcorec, vrcorew, nvor, rv1, rv1_diff, rv2
     +            , rv2_diff, lvcomp, chordv, chordv_diff, nvor, rv, 
     +            rv_diff, lvcomp, .true., wv_gam, wv_gam_diff, nvor)
C
      CALL SRDSET_D(betm, betm_diff, xyzref, xyzref_diff, iysym, nbody, 
     +              lfrst, nlmax, numax, nl, rl, rl_diff, radl, src_u, 
     +              src_u_diff, dbl_u, dbl_u_diff)
C
      CALL VSRD_D(betm, betm_diff, iysym, ysym, ysym_diff, izsym, zsym, 
     +            zsym_diff, srcore, nbody, lfrst, nlmax, nl, rl, 
     +            rl_diff, radl, numax, src_u, src_u_diff, dbl_u, 
     +            dbl_u_diff, nvor, rc, rc_diff, wcsrd_u, wcsrd_u_diff, 
     +            nvmax)
C
C---- set VINF() vector from initial ALFA,BETA
      CALL VINFAB_D()
      DO ii1=1,nlmax
        src_diff(ii1) = 0.D0
      ENDDO
      DO l=1,nlnode
        src_diff(l) = vinf(1)*src_u_diff(l, 1) + src_u(l, 1)*vinf_diff(1
     +    ) + vinf(2)*src_u_diff(l, 2) + src_u(l, 2)*vinf_diff(2) + vinf
     +    (3)*src_u_diff(l, 3) + src_u(l, 3)*vinf_diff(3) + wrot(1)*
     +    src_u_diff(l, 4) + src_u(l, 4)*wrot_diff(1) + wrot(2)*
     +    src_u_diff(l, 5) + src_u(l, 5)*wrot_diff(2) + wrot(3)*
     +    src_u_diff(l, 6) + src_u(l, 6)*wrot_diff(3)
        src(l) = src_u(l, 1)*vinf(1) + src_u(l, 2)*vinf(2) + src_u(l, 3)
     +    *vinf(3) + src_u(l, 4)*wrot(1) + src_u(l, 5)*wrot(2) + src_u(l
     +    , 6)*wrot(3)
      ENDDO
      DO ii1=1,numax
        DO ii2=1,nvor
          rhs_u_diff(ii2, ii1) = 0.D0
        ENDDO
      ENDDO
      DO ii1=1,numax
        DO ii2=1,nvor
          res_u_diff(ii2, ii1) = 0.D0
        ENDDO
      ENDDO
      DO iu=1,6
        CALL MAT_PROD_D(aicn, aicn_diff, gam_u(:, iu), gam_u_diff(:, iu)
     +                  , nvor, res_u(:, iu), res_u_diff(:, iu))
        CALL SET_VEL_RHS_U_D(iu)
        DO i=1,nvor
          res_u_diff(i, iu) = res_u_diff(i, iu) - rhs_u_diff(i, iu)
          res_u(i, iu) = res_u(i, iu) - rhs_u(i, iu)
        ENDDO
      ENDDO
      CALL SET_VEL_RHS_D()
C
C$AD II-LOOP
      CALL MAT_PROD_D(aicn, aicn_diff, gam, gam_diff, nvor, res, 
     +                res_diff)
C---- add the RHS vector to the residual
      DO i=1,nvor
        res_diff(i) = res_diff(i) - rhs_diff(i)
        res(i) = res(i) - rhs(i)
C$AD II-LOOP
      ENDDO
      DO ii1=1,ndmax
        DO ii2=1,nvor
          res_d_diff(ii2, ii1) = 0.D0
        ENDDO
      ENDDO
      DO ii1=1,nvor
        rhs_d_diff(ii1) = 0.D0
      ENDDO
      DO ic=1,ncontrol
C------ don't bother if this control variable is undefined
        IF (lcondef(ic)) THEN
C  RHS_D(:) = 0.D0
          CALL MAT_PROD_D(aicn, aicn_diff, gam_d(:, ic), gam_d_diff(:, 
     +                    ic), nvor, res_d(:, ic), res_d_diff(:, ic))
C$AD II-LOOP
          CALL SET_GAM_D_RHS_D(ic, enc_d, enc_d_diff, rhs_d, rhs_d_diff)
          DO i=1,nvor
            res_d_diff(i, ic) = res_d_diff(i, ic) - rhs_d_diff(i)
            res_d(i, ic) = res_d(i, ic) - rhs_d(i)
          ENDDO
        END IF
      ENDDO
C

      END

